<Project Sdk="MSTest.Sdk/4.1.0">
  <PropertyGroup>
    <RootNamespace>Marginalia.Api.Client.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Client\Api\Marginalia.Api.Client.csproj" />
  </ItemGroup>
</Project>
