<Project Sdk="MSTest.Sdk/4.1.0">
  <PropertyGroup>
    <RootNamespace>Marginalia.Tools.Cli.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Tools\Cli\Marginalia.Tools.Cli.csproj" />
  </ItemGroup>
</Project>
