<Project Sdk="MSTest.Sdk/4.1.0">

  <PropertyGroup>
    <RootNamespace>Marginalia.Domain.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Domain\Marginalia.Domain.csproj" />
  </ItemGroup>

</Project>
