<Project Sdk="MSTest.Sdk/4.1.0">

  <PropertyGroup>
    <RootNamespace>Marginalia.Api.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Api\Marginalia.Api.csproj" />
    <ProjectReference Include="..\..\..\src\Orchestration\ServiceDefaults\Marginalia.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
